dist: focal
language: node_js
node_js: '18'
cache: npm
before_install:
    - npm config set @schibsted:registry=https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken=${NPMJS_AUTHTOKEN}
install: npm ci
script:
    - npm run cover
    - npm run build
    - npm run docs
deploy:
  - provider: script
    skip_cleanup: true
    script: npm publish --access=public --tag beta
    on:
      branch: master
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
